import train_and_test

EPISODE_LENGTHS = [500]
MINIBATCH_SIZES = [300]
DISCOUNTS = [0.98]
EPSILON_DECAYS = [0.99,0.995]
TARGET_UPDATES = [2]


for EPISODE_LENGTH in EPISODE_LENGTHS:
    for MINIBATCH_SIZE in MINIBATCH_SIZES:
        for DISCOUNT in DISCOUNTS:
            for EPSILON_DECAY in EPSILON_DECAYS:
                for TARGET_UPDATE in TARGET_UPDATES: 
                        train_and_test.main(EPISODE_LENGTH, MINIBATCH_SIZE, DISCOUNT, EPSILON_DECAY, TARGET_UPDATE)
    
    